version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - server
    groups:
      types:
        patterns:
          - "@types/*"
      eslint:
        patterns:
          - "eslint*"
          - "@typescript-eslint/*"

  - package-ecosystem: npm
    directory: "/client"
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - client
    groups:
      types:
        patterns:
          - "@types/*"
      tailwind:
        patterns:
          - "tailwindcss"
          - "@tailwindcss/*"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    labels:
      - dependencies
      - ci

  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: weekly
    labels:
      - dependencies
      - docker
